### ISSUE TITLE
Version 2 API Release checklist

### ISSUE THREAD

**Issue by MrRefactoring** [MrRefactoring/confluence.js#43]
- [ ] `blogPost.createBlogPost` method has `data` property.
- [ ] `blogPost.updateBlogPost` method has `data` property.
- [ ] `blogPost.getBlogPostById` properties with dash (`-`) replaced to `camelCase`
- [ ] `comment.getPageFooterComments` properties with dash (`-`) replaced to `camelCase`
- [ ] `comment.getPageInlineComments` properties with dash (`-`) replaced to `camelCase`
- [ ] `comment.getBlogPostFooterComments` properties with dash (`-`) replaced to `camelCase`
- [ ] `comment.getBlogPostInlineComments` properties with dash (`-`) replaced to `camelCase`
- [ ] `comment.createFooterComment` have optional parameters. It's okay?
